env:
  browser: true
  es6: true
extends: 'eslint:recommended'
rules:
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
    - windows
  semi:
    - error
    - always
  no-console    : 0
  no-undef      : 0
  no-unused-vars: 0